/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement.view.viewTest;

import hotelmanagement.view.*;
import hotelmanagement.controller.StaffController;
import hotelmanagement.model.StaffModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tung
 */
public class StaffManagement extends javax.swing.JFrame {

    //Tao doi tuong staffController
    StaffController staffController = new StaffController();

    public StaffManagement() {
        initComponents();
        this.qlns_showTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_info = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        qlns_hovaten = new javax.swing.JTextField();
        qlns_taikhoan = new javax.swing.JTextField();
        qlns_matkhau = new javax.swing.JTextField();
        qlns_email = new javax.swing.JTextField();
        qlns_diachi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        qlns_chucvu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        qlns_sdt = new javax.swing.JTextField();
        qlns_gioitinh = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        qlns_table = new javax.swing.JTable();
        qlns_but_add = new javax.swing.JButton();
        qlns_but_del = new javax.swing.JButton();
        qlns_but_edit = new javax.swing.JButton();
        qlns_but_update = new javax.swing.JButton();
        qlns_but_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Arrus-Black", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ NHÂN SỰ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Họ và tên:");

        qlns_hovaten.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        qlns_hovaten.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlns_hovaten.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        qlns_hovaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_hovatenActionPerformed(evt);
            }
        });

        qlns_taikhoan.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        qlns_taikhoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlns_taikhoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        qlns_taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_taikhoanActionPerformed(evt);
            }
        });

        qlns_matkhau.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        qlns_matkhau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlns_matkhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        qlns_matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_matkhauActionPerformed(evt);
            }
        });

        qlns_email.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        qlns_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlns_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        qlns_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_emailActionPerformed(evt);
            }
        });

        qlns_diachi.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        qlns_diachi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlns_diachi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        qlns_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_diachiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tài khoản:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mật khẩu:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Giới tính:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Địa chỉ:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Chức vụ:");

        qlns_chucvu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        qlns_chucvu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlns_chucvu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        qlns_chucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_chucvuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SĐT:");

        qlns_sdt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        qlns_sdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlns_sdt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        qlns_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_sdtActionPerformed(evt);
            }
        });

        qlns_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout jPanel_infoLayout = new javax.swing.GroupLayout(jPanel_info);
        jPanel_info.setLayout(jPanel_infoLayout);
        jPanel_infoLayout.setHorizontalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(qlns_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_infoLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(qlns_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_infoLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qlns_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_infoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qlns_hovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qlns_diachi, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(qlns_email, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(qlns_chucvu, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(qlns_gioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_infoLayout.setVerticalGroup(
            jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_infoLayout.createSequentialGroup()
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_infoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(qlns_hovaten, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_infoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qlns_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlns_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlns_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(qlns_gioitinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlns_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlns_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlns_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        qlns_table.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));
        qlns_table.setForeground(new java.awt.Color(0, 153, 255));
        qlns_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        qlns_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        qlns_table.setSelectionBackground(new java.awt.Color(102, 204, 255));
        qlns_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        qlns_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qlns_tableMouseClicked(evt);
            }
        });
        qlns_table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                qlns_tableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(qlns_table);
        qlns_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        qlns_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        qlns_but_add.setBackground(new java.awt.Color(0, 204, 255));
        qlns_but_add.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        qlns_but_add.setText("Thêm");
        qlns_but_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_but_addActionPerformed(evt);
            }
        });

        qlns_but_del.setBackground(new java.awt.Color(0, 153, 255));
        qlns_but_del.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        qlns_but_del.setText("Xóa");
        qlns_but_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_but_delActionPerformed(evt);
            }
        });

        qlns_but_edit.setBackground(new java.awt.Color(0, 204, 204));
        qlns_but_edit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        qlns_but_edit.setText("Sửa");
        qlns_but_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_but_editActionPerformed(evt);
            }
        });

        qlns_but_update.setBackground(new java.awt.Color(153, 153, 255));
        qlns_but_update.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        qlns_but_update.setText("Cập nhật");
        qlns_but_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_but_updateActionPerformed(evt);
            }
        });

        qlns_but_back.setBackground(new java.awt.Color(204, 204, 204));
        qlns_but_back.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        qlns_but_back.setText("Quay lại");
        qlns_but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlns_but_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qlns_but_add, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qlns_but_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qlns_but_del, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qlns_but_update)
                        .addGap(107, 107, 107)
                        .addComponent(qlns_but_back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(367, 367, 367))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qlns_but_add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qlns_but_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qlns_but_del, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(qlns_but_back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qlns_but_update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qlns_hovatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_hovatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlns_hovatenActionPerformed

    private void qlns_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_taikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlns_taikhoanActionPerformed

    private void qlns_matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_matkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlns_matkhauActionPerformed

    private void qlns_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlns_emailActionPerformed

    private void qlns_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlns_diachiActionPerformed

    private void qlns_chucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_chucvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlns_chucvuActionPerformed

    private void qlns_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlns_sdtActionPerformed

    private void qlns_but_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_but_delActionPerformed
        // Used
    }//GEN-LAST:event_qlns_but_delActionPerformed

    private void qlns_but_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_but_updateActionPerformed
        // Used
    }//GEN-LAST:event_qlns_but_updateActionPerformed

    private void qlns_but_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_but_editActionPerformed
        // Used
    }//GEN-LAST:event_qlns_but_editActionPerformed

    private void qlns_but_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_but_addActionPerformed
        // TODO add your handling code here:
        String name = qlns_hovaten.getText();
        String username = qlns_taikhoan.getText();
        String password = qlns_matkhau.getText();
        String email = qlns_email.getText();
        String phoneNumber = qlns_sdt.getText();
        String gender = (String) qlns_gioitinh.getSelectedItem();
        String address = qlns_diachi.getText();
        String role = qlns_chucvu.getText();
        if (name.isEmpty() || username.isEmpty() || password.isEmpty() || email.isEmpty() || phoneNumber.isEmpty() || gender.isEmpty() || role.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        } else {
            //Call create user here
            try {
                int Role = Integer.parseInt(role);
                //Gọi phương thức create trong StaffModel
                staffController.create(username, password, name, phoneNumber, email, gender, address, Role);
                resetTextField();
                qlns_showTable();
            } catch (Exception e) {
                // Console Log if error
                JOptionPane.showMessageDialog(this, "Error creating user: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_qlns_but_addActionPerformed

    void qlns_showTable() {
        // TODO add your handling code here:
        ArrayList<StaffModel> staffs = staffController.getAll();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Tất cả các ô không thể chỉnh sửa
            }
        };
        model.addColumn("Staff ID");
        model.addColumn("Name");
        model.addColumn("Username");
        model.addColumn("Phone Number");
        model.addColumn("Email");
        model.addColumn("Address");
        model.addColumn("Gender");
        model.addColumn("Role");

        // Thêm dữ liệu từ danh sách staffs vào DefaultTableModel
        for (StaffModel staff : staffs) {
            Object[] rowData = {
                staff.getstaffId(),
                staff.getName(),
                staff.getUsername(),
                staff.getPhoneNumber(),
                staff.getEmail(),
                staff.getAddress(),
                staff.getGender(),
                staff.getRole()
            };
            model.addRow(rowData);
        }
        // Đặt DefaultTableModel cho JTable
        qlns_table.setModel(model);

    }

    private void qlns_tableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_qlns_tableComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_qlns_tableComponentShown

    private void qlns_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qlns_tableMouseClicked
        // TODO add your handling code here:

        // Thêm ActionListener cho sự kiện nhấp nút (ví dụ: "Edit" button)
        qlns_but_edit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Lấy chỉ số hàng được chọn
                int selectedRow = qlns_table.getSelectedRow();

                // Kiểm tra xem có hàng nào được chọn không
                if (selectedRow != -1) {
                    // Lấy dữ liệu từ hàng được chọn và làm việc với nó
                    TableModel tableModel = qlns_table.getModel();
                    Object name = tableModel.getValueAt(selectedRow, 1);
                    Object username = tableModel.getValueAt(selectedRow, 2);
                    Object phoneNumber = tableModel.getValueAt(selectedRow, 3);
                    Object email = tableModel.getValueAt(selectedRow, 4);
                    Object address = tableModel.getValueAt(selectedRow, 5);
                    Object gender = tableModel.getValueAt(selectedRow, 6);
                    Object role = tableModel.getValueAt(selectedRow, 7);

                    // Thực hiện xử lý chỉnh sửa dữ liệu ở đây
                    // Ví dụ: Hiển thị dữ liệu trong các trường JTextField
                    qlns_hovaten.setText(name.toString());
                    qlns_taikhoan.setText(username.toString());
                    qlns_sdt.setText(phoneNumber.toString());
                    qlns_email.setText(email.toString());
                    qlns_diachi.setText(address.toString());
                    qlns_gioitinh.setSelectedItem(gender.toString());
                    qlns_chucvu.setText(role.toString());

                }
            }
        });
        qlns_but_update.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Lấy chỉ số hàng được chọn
                int selectedRow = qlns_table.getSelectedRow();

                // Kiểm tra xem có hàng nào được chọn không
                if (selectedRow != -1) {
                    // Lấy dữ liệu từ hàng được chọn và làm việc với nó
                    TableModel tableModel = qlns_table.getModel();
                    int staffId = (int) tableModel.getValueAt(selectedRow, 0);
//                    String name = tableModel.getValueAt(selectedRow, 1).toString();
//                    String username = tableModel.getValueAt(selectedRow, 2).toString();
//                    String phoneNumber = tableModel.getValueAt(selectedRow, 3).toString();
//                    String email = tableModel.getValueAt(selectedRow, 4).toString();
//                    String address = tableModel.getValueAt(selectedRow, 5).toString();
//                    String gender = tableModel.getValueAt(selectedRow, 6).toString();
//                    int role = (int)tableModel.getValueAt(selectedRow, 7);
//                    String password = qlns_matkhau.getText();
                    String name = qlns_hovaten.getText();
                    String username = qlns_taikhoan.getText();
                    String phoneNumber = qlns_sdt.getText();
                    String email = qlns_email.getText();
                    String address = qlns_diachi.getText();
                    String gender = (String) qlns_gioitinh.getSelectedItem();
                    String password = qlns_matkhau.getText();
                    int role = Integer.parseInt(qlns_chucvu.getText());
                    staffController.update(username, password, name, phoneNumber, email, gender, address, role, staffId);
                    resetTextField();
                    qlns_showTable();
                }
            }
        });
        qlns_but_del.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Lấy chỉ số hàng được chọn
                int selectedRow = qlns_table.getSelectedRow();

                // Kiểm tra xem có hàng nào được chọn không
                if (selectedRow != -1) {
                    // Lấy dữ liệu từ hàng được chọn và làm việc với nó
                    TableModel tableModel = qlns_table.getModel();
                    int staffId = (int) tableModel.getValueAt(selectedRow, 0);
                    staffController.delete(staffId);
                    resetTextField();
                    qlns_showTable();
                }
            }
        });
    }//GEN-LAST:event_qlns_tableMouseClicked

    private void qlns_but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlns_but_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HotelManager hotelManagerView = new HotelManager();
        hotelManagerView.setVisible(true);
    }//GEN-LAST:event_qlns_but_backActionPerformed

    public void displayErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(this, errorMessage);
    }

    public void resetTextField() {
        //Thuc hien reset cac truong nhap du lieu!
        qlns_taikhoan.setText("");
        qlns_matkhau.setText("");
        qlns_sdt.setText("");
        qlns_chucvu.setText("");
        qlns_diachi.setText("");
        qlns_gioitinh.setSelectedItem("");
        qlns_email.setText("");
        qlns_hovaten.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton qlns_but_add;
    private javax.swing.JButton qlns_but_back;
    private javax.swing.JButton qlns_but_del;
    private javax.swing.JButton qlns_but_edit;
    private javax.swing.JButton qlns_but_update;
    public javax.swing.JTextField qlns_chucvu;
    public javax.swing.JTextField qlns_diachi;
    public javax.swing.JTextField qlns_email;
    private javax.swing.JComboBox<String> qlns_gioitinh;
    public javax.swing.JTextField qlns_hovaten;
    public javax.swing.JTextField qlns_matkhau;
    public javax.swing.JTextField qlns_sdt;
    private javax.swing.JTable qlns_table;
    public javax.swing.JTextField qlns_taikhoan;
    // End of variables declaration//GEN-END:variables
}
